{"name": "登录密码错误", "status": "passed", "description": "登录失败用例", "attachments": [{"name": "stdout", "source": "8ed91871-a07b-4ba6-bfd4-10396d4e3a1c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'test10'"}, {"name": "psw", "value": "'123321'"}, {"name": "title", "value": "'登录密码错误'"}], "start": 1639015539265, "stop": 1639015539511, "uuid": "a50dfeff-b61a-4f6c-97e1-3b41869d0416", "historyId": "c811ce9a00dcc9a6af4dcfb556ceec70", "testCaseId": "04e9502b72231c99b3e3fd3a8c6be39d", "fullName": "test_case.test_login.Test_login#test_login_fail", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "登录失败用例"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "v_qangchen-PC1"}, {"name": "thread", "value": "70196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login"}]}