{"name": "登录账号错误", "status": "passed", "description": "登录失败用例", "attachments": [{"name": "stdout", "source": "455ae372-6a5a-4369-b982-d8f9a516be84-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'aaxxxx01'"}, {"name": "psw", "value": "'123456'"}, {"name": "title", "value": "'登录账号错误'"}], "start": 1639448464748, "stop": 1639448464959, "uuid": "100b389b-3424-4552-9c8e-e94be0e44958", "historyId": "8ea5593a0a443cf97841c89113ef0174", "testCaseId": "04e9502b72231c99b3e3fd3a8c6be39d", "fullName": "test_case.test_login.Test_login#test_login_fail", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "登录失败用例"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "v_qangchen-PC1"}, {"name": "thread", "value": "7628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login"}]}